### ISSUE TITLE
7 vulnerabilities in dependences

### ISSUE THREAD

**Issue by iamyulong** [aionnetwork/aion_web3#15]
```
$ npm install
added 561 packages from 835 contributors and audited 2577 packages in 11.692s
found 7 vulnerabilities (2 low, 1 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
```

**Comment by tcrowe** [comment]
Usually these `npm audit` reports are not important but you have a few options:

+ Believe it's important and seek to get it resolved
+ Make the case to aion devs if it's important
+ Repeat `npm audit fix` until its fixed
+ Ignore it and make npm be quiet https://gist.github.com/tcrowe/19b2469838919535a7ba2b43d29c97f2

What do you want to do?

**Comment by aion-kelvin** [comment]
Hey yulong,

I believe that this problem only occurs on the master branch, which actually contains outdated code and we're not developing or releasing from it anymore.  The branch "v1.0" is the branch that we're actually developing on.  Can you confirm if you see that message when you use "v1.0" branch?  If this problem is only on master I think we can close this issue.

For me when I run `npm install` on v1.0:

```
$ npm install

> aion-web3@1.0.0 postinstall /home/sergiu/repos/aion_web3
> lerna bootstrap

lerna info version 2.11.0
lerna info Bootstrapping 18 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna info lifecycle postinstall
lerna info lifecycle prepublish
lerna info lifecycle prepare
lerna success Bootstrapped 18 packages
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 6319 packages in 6.909s
found 0 vulnerabilities

```

(I also tried npm install on master branch and I do indeed see seven vulnerabilities).

**Comment by aion-kelvin** [comment]
Haven't heard back so assuming it's fixed. @yulongaion  Feel free to re-open / make a new issue / message me if there's further concerns/problems
