### ISSUE TITLE
We may be paying for more gas than necessary

### ISSUE THREAD

**Issue by qoire** [aionnetwork/aion_web3#31]
As pointed out by Sergiu, we might be padding our transactions by default with ``0x00``, which is treated as data input. This implicitly leads to an increase over the ambient base gas cost of ``21000``.

**Comment by aion-kelvin** [comment]
One way to check this:

1) use web3's signTransaction and sendRawTransaction to send some aions on mastery (omit the `data` field) -- i.e. the same thing as what this test does: https://github.com/aionnetwork/aion_web3/blob/v1.0/integ_test/send_raw_transaction.js
2) use a debugger on the kernel to look at the transaction coming in and make sure there's no 0x00 in the `data` field
3) use mastery dashboard to look up the transaction and make sure there's no `data`
4) repeat the test using server-side signing (sendTransaction instead of sendRawTransaction) to make sure that also does not put a `data` field

**Comment by arajasek** [comment]
I took a close look at this, tried pretty much every combination of signing and sending transactions. Never got a data="0x00" field in any of my transactions.

I checked both the transaction content in the kernel itself, and what can be seen on the dashboard, it all seems fine.
