### ISSUE TITLE
Broken npm to GitHub link

### ISSUE THREAD

**Issue by erik-iglikov** [aionnetwork/aion_web3#45]
In the npm page for `aion-web3-core`(https://www.npmjs.com/package/aion-web3-core) the link goes to `https://github.com/aionnetwork/aion_web3/tree/master/packages/web3-core` which routes to 404 page

**Comment by aion-kelvin** [comment]
fixed in https://github.com/aionnetwork/aion_web3/commit/11a82eca94b85c781258850951d4bdb50d7e8ce8

I noticed the other subpackages have this problem so I'll update them too.

**Comment by aion-kelvin** [comment]
THere's another issue open that's about addressing the overall consistency of the documentation in aion-web3 and all the subpackages -- https://github.com/aionnetwork/aion_web3/issues/36.  Since the specific example in this one is fixed ,I'm going to close this issue and just track this general problem in that issue.
