### ISSUE TITLE
signTransaction signing a transaction with incorrect value

### ISSUE THREAD

**Issue by aionick** [aionnetwork/aion_web3#64]
@arajasek and I have confirmed that this issue seems to reside specifically in the command `web3.eth.accounts.signTransaction()`. After calling this function on a transaction with some value **x** we then took the raw encoded bytes and decoded them using the `AionTransaction` class's rlp decoding and this produced a transaction with the incorrect value **y != x.**

We should probably be patching this and verifying _all_ of the fields of the transaction are correct, not just value.

We suspected that the value we thought we were entering in decimal was actually being interpreted as hex - this is **wrong** and is not what is happening.

For more context see this issue [here](https://github.com/aionnetwork/aion_rlp.js/issues/1).

**Comment by aion-kelvin** [comment]
Investigated w/ Aayush.

The root of the problem is that in signTransaction, numerical fields can be provided as Javascript numbers (i.e. `123`), strings (i.e. `0xabc` or `0x123`), or BN (BigNumber).  Strings should be interpreted as decimal numbers if it does not begin with `0x`, or hex if it does.  It incorrectly interpreted them as hex all the time.  

The reason for the dec/hex issue is that at the start of signTransaction, it's supposed to run an a helper method `formatters.inputCallFormatter`, but it was commented out.  The formatter massages the tx object to become a string containing a hex number (`0x123abc`).  Because of this, the dec input is interpreted as hex.  Afterward, the value is passed to helper method `toAionLong` which has some unintuitive behaviour when its input is not a string containing a hex number, which further mangled the number.

PR for the fix is out, which is to just make sure the formatter runs.  We should also look into whether `toAionLong` needs to be made more intuitive so it doesn't cause any further mistakes down the road.
